// Report data — separated from the client component to avoid
// server/client serialization issues during prerendering.
import type { ReportData } from "./InsightReportTemplate";

export const REPORT_DATA: Record<string, ReportData> = {
  risk: {
    slug: "risk",
    eyebrow: "Risk Reports",
    title: "32-category risk assessment with mitigation plan.",
    tagline: "Know every risk that could hit your business — and what to do about each one.",
    intro: "Our Risk Report scans 30+ media sources to detect risks across 32 categories specific to your industry. Each risk is scored on Frequency × Impact × Velocity, with trajectory tracking and AI-generated mitigation recommendations. Delivered as a board-ready PDF in 5 days.",
    color: "#A0524B",
    pages: 18,
    deliveryTime: "5 business days",
    format: "PDF + 1-hour analyst briefing",
    stats: [
      { value: "32", label: "risk categories assessed" },
      { value: "5", label: "business days delivery" },
      { value: "Top 10", label: "active risks ranked" },
      { value: "1h", label: "analyst briefing included" },
    ],
    whatsIncluded: [
      "32-category risk scan (geopolitical, operational, financial, environmental, legal, consumer, technology, governance)",
      "Top 10 active risks with composite scoring",
      "Frequency × Impact × Velocity breakdown per risk",
      "Trajectory tracking (rising/stable/declining)",
      "AI-generated mitigation recommendations per risk",
      "Industry-specific risk weighting applied",
      "Emerging risk detection (velocity > 30% in 24h)",
      "Comparison vs industry peers",
      "Executive summary (2 pages)",
      "Detailed risk register (12 pages)",
      "Mitigation action plan with timeline (3 pages)",
      "Methodology appendix (1 page)",
    ],
    whatsInside: [
      { section: "Executive Summary", desc: "1-page overview: overall risk score, top 3 risks, recommended immediate actions." },
      { section: "Risk Score Dashboard", desc: "Visual dashboard: overall risk score (0-100), risk level, trajectory, comparison vs industry average." },
      { section: "Top 10 Active Risks", desc: "Detailed breakdown of the 10 highest-scoring risks: category, frequency, impact, velocity, score, trajectory, articles affected." },
      { section: "Risk by Category", desc: "32-category heatmap showing which risk categories are active for your company." },
      { section: "Industry Comparison", desc: "How your risk profile compares to industry peers — are you more or less exposed?" },
      { section: "Emerging Risks", desc: "Risks with rising velocity in the last 7 days. Catch them before they escalate." },
      { section: "Mitigation Plan", desc: "For each top risk: specific actions, who to engage, timeline, expected impact on score." },
      { section: "90-Day Action Plan", desc: "Week-by-week milestones with ownership assignments." },
      { section: "Methodology", desc: "How we scored: data sources, weighting formula, confidence intervals." },
    ],
    sampleQuestions: [
      "What are our top 3 operational risks right now?",
      "How does our risk profile compare to competitors?",
      "Which emerging risks should we monitor in the next 90 days?",
      "What's our risk trajectory — improving or deteriorating?",
      "Which mitigation actions will have the biggest impact on our score?",
      "Are we more exposed to cyber risk than industry peers?",
      "What regulatory risks are on the horizon?",
      "How is the geopolitical environment affecting our risk profile?",
    ],
    pricing: [
      { tier: "One-time", price: "12,000 MAD", frequency: "single report", features: ["18-page PDF", "1-hour analyst briefing", "30-day access to dashboard", "Email support"] },
      { tier: "Quarterly", price: "8,000 MAD", frequency: "per quarter (4 reports/year)", features: ["4 reports per year", "Quarterly analyst briefing", "90-day dashboard access", "Priority email support", "Year-over-year comparison"] },
      { tier: "Monthly", price: "6,000 MAD", frequency: "per month (12 reports/year)", features: ["12 reports per year", "Monthly analyst briefing", "Continuous dashboard access", "24/7 priority support", "Custom risk taxonomy", "Crisis playbook templates"] },
    ],
  },

  "reputation-risk": {
    slug: "reputation-risk",
    eyebrow: "Reputation Risk Reports",
    title: "Reputation exposure analysis with narrative detection.",
    tagline: "See every narrative forming around your brand — and which ones threaten your reputation.",
    intro: "Your reputation is the sum of narratives forming about you. Our Reputation Risk Report identifies the 5 dominant narratives, scores their strength and sentiment, and flags which ones pose a threat. Includes crisis playbook for high-risk narratives.",
    color: "#A02828",
    pages: 16,
    deliveryTime: "5 business days",
    format: "PDF + crisis playbook template",
    stats: [
      { value: "5", label: "narratives analyzed" },
      { value: "10", label: "topic clusters tracked" },
      { value: "Trilingual", label: "FR · AR · EN analysis" },
      { value: "Crisis", label: "playbook included" },
    ],
    whatsIncluded: [
      "5 dominant narratives with strength scoring (0-100)",
      "Narrative trajectory (emerging/growing/peak/declining)",
      "Sentiment per narrative (-1 to +1)",
      "Article count per narrative",
      "10 topic clusters with sentiment distribution",
      "Entity-level sentiment (company, CEO, products)",
      "Trilingual sentiment analysis (FR/AR/EN)",
      "Negative sentiment velocity alerts",
      "Crisis playbook for top 3 threatening narratives",
      "Source authority analysis (which outlets amplify each narrative)",
      "Reputation risk score (0-100)",
      "Comparison vs industry reputation average",
    ],
    whatsInside: [
      { section: "Executive Summary", desc: "Reputation risk score, top 3 threatening narratives, immediate actions." },
      { section: "Narrative Map", desc: "Visual map of all 5 narratives — strength vs sentiment, with trajectory arrows." },
      { section: "Top 5 Narratives Deep Dive", desc: "For each: narrative statement, strength, sentiment, article count, trajectory, key articles, source breakdown." },
      { section: "Threat Assessment", desc: "Which narratives pose the biggest reputation risk? Severity scoring + escalation probability." },
      { section: "Crisis Playbook", desc: "For top 3 threats: holding statements, spokesperson talking points, escalation protocols, monitoring triggers." },
      { section: "Sentiment Analysis", desc: "Trilingual sentiment breakdown (FR/AR/EN), per-source, per-topic, per-entity." },
      { section: "Source Authority Map", desc: "Which outlets amplify each narrative? Authority × reach × sentiment per source." },
      { section: "Recovery Roadmap", desc: "If reputation is damaged: 30/60/90 day recovery plan with milestones." },
    ],
    sampleQuestions: [
      "What are the dominant narratives forming around our brand?",
      "Which narrative poses the biggest threat to our reputation?",
      "How is our CEO perceived in the media vs. our competitors' CEOs?",
      "What's our reputation risk score and how does it compare to industry?",
      "Which outlets are amplifying negative narratives about us?",
      "Is our reputation recovering from the recent crisis?",
      "What holding statement should we prepare for the labor dispute narrative?",
      "Which topics are driving negative sentiment?",
    ],
    pricing: [
      { tier: "One-time", price: "14,000 MAD", frequency: "single report", features: ["16-page PDF", "Crisis playbook template", "30-day dashboard access", "1-hour analyst briefing"] },
      { tier: "Quarterly", price: "10,000 MAD", frequency: "per quarter", features: ["4 reports per year", "Updated crisis playbook", "90-day dashboard access", "Priority support", "Narrative tracking history"] },
      { tier: "Monthly", price: "8,000 MAD", frequency: "per month", features: ["12 reports per year", "Custom narrative tracking", "Continuous dashboard", "24/7 crisis support", "Real-time WhatsApp alerts", "Spokesperson training pack"] },
    ],
  },

  reputation: {
    slug: "reputation",
    eyebrow: "Reputation Reports",
    title: "Full reputation audit with score & pillars.",
    tagline: "Your complete reputation profile — score, pillars, themes, competitors, recommendations.",
    intro: "The Reputation Report is our flagship deliverable. It includes everything: reputation score (0-100), Innovation/Performance/Purpose pillars, 9 key themes, top 30 articles, topic clustering, narratives, risks, competitor benchmarks, and prioritized recommendations with 90-day action plan.",
    color: "#4A7B5F",
    pages: 24,
    deliveryTime: "7 business days",
    format: "PDF + executive presentation deck",
    stats: [
      { value: "24", label: "pages, board-ready" },
      { value: "0-100", label: "reputation score" },
      { value: "9", label: "key themes scored" },
      { value: "5", label: "competitors benchmarked" },
    ],
    whatsIncluded: [
      "Reputation score (0-100) with 4 components: sentiment × AI visibility × volume × authority",
      "Innovation / Performance / Purpose pillars (Signal AI 500 style)",
      "9 key themes: Collaborations, Products, Technology, Governance, Growth, Operations, CSR, Culture, Sustainability",
      "Top 30 articles by relevance (with sentiment + source authority)",
      "10 topic clusters with sentiment distribution",
      "5 dominant narratives with strength scoring",
      "Top 5 active risks with mitigation recommendations",
      "5 competitor benchmarks (score, share of voice, sentiment gap)",
      "Quarterly trend tracking (4Q historical)",
      "AI visibility matrix (4 engines × citation status)",
      "Share of conversation vs industry total",
      "Prioritized recommendations with timeline and owner",
      "90-day action plan (week-by-week milestones)",
      "Methodology and sources appendix",
    ],
    whatsInside: [
      { section: "Cover & Executive Summary", desc: "Reputation score, key findings, top 3 recommendations. 2 pages." },
      { section: "Reputation Score Breakdown", desc: "Score (0-100) decomposed into 4 components with weights and industry benchmark." },
      { section: "Pillars: Innovation / Performance / Purpose", desc: "Which pillar dominates your narrative? Weight %, score, themes per pillar." },
      { section: "Sentiment Analysis Deep Dive", desc: "Trilingual sentiment breakdown (FR/AR/EN), per source, per topic, per entity." },
      { section: "AI Visibility Matrix", desc: "4 AI engines (ChatGPT, Perplexity, Gemini, Claude) — cited? position? sentiment?" },
      { section: "Top 30 Articles", desc: "Highest-relevance articles with full metadata, sentiment, source authority." },
      { section: "Topic Clustering", desc: "10 topic clusters with article count, sentiment distribution, risk level, trend." },
      { section: "Narrative Detection", desc: "5 dominant narratives with strength, sentiment, trajectory, article count." },
      { section: "Risk Assessment", desc: "Top 5 active risks with Frequency × Impact × Velocity + mitigation." },
      { section: "Competitor Benchmarking", desc: "5 competitors compared: score, share of voice, sentiment gap, AI visibility gap." },
      { section: "Strategic Recommendations", desc: "7 prioritized recommendations (critical/high/medium/low) with timeline and owner." },
      { section: "90-Day Action Plan", desc: "Week-by-week milestones with owner assignments and KPIs." },
      { section: "Methodology & Sources", desc: "Data sources, scoring formula, confidence intervals, top 10 sources by volume." },
    ],
    sampleQuestions: [
      "What's our reputation score and how has it evolved?",
      "Which pillar (Innovation/Performance/Purpose) dominates our narrative?",
      "How do we compare to our top 5 competitors?",
      "What are our 5 dominant narratives?",
      "Which AI engines cite us when prospects ask about our industry?",
      "What's our share of voice vs. competitors?",
      "What are the top 3 actions we should take in the next 90 days?",
      "How is our sentiment trending across FR/AR/EN media?",
    ],
    pricing: [
      { tier: "One-time", price: "25,000 MAD", frequency: "single report", features: ["24-page PDF", "Executive deck (15 slides)", "2-hour analyst briefing", "30-day dashboard access", "Custom research questions"] },
      { tier: "Quarterly", price: "18,000 MAD", frequency: "per quarter", features: ["4 reports per year", "Updated executive deck", "Quarterly analyst briefing", "90-day dashboard", "Year-over-year trends"] },
      { tier: "Monthly (Enterprise)", price: "15,000 MAD", frequency: "per month", features: ["12 reports per year", "Monthly executive deck", "Dedicated analyst", "Continuous dashboard", "24/7 priority support", "Custom pillar definitions", "Board presentation prep"] },
    ],
  },

  "media-impact": {
    slug: "media-impact",
    eyebrow: "Media Impact Reports",
    title: "PR campaign measurement with share of voice.",
    tagline: "Did your PR campaign actually move the needle? Now you can prove it.",
    intro: "Stop measuring PR with AVE (ad value equivalence) — it's 2026. Our Media Impact Report measures what actually matters: sentiment shift, share of voice movement, narrative resonance, source pickup, AI engine pickup. Before/during/after comparison proves ROI.",
    color: "#4A5D6E",
    pages: 14,
    deliveryTime: "5 business days after campaign end",
    format: "PDF + before/after dashboard",
    stats: [
      { value: "Before/After", label: "comparison included" },
      { value: "10+", label: "metrics measured" },
      { value: "AI engines", label: "tracked for pickup" },
      { value: "Source", label: "authority weighted" },
    ],
    whatsIncluded: [
      "Before/during/after comparison (T-30 days vs campaign vs T+30 days)",
      "Volume spike analysis (article count delta)",
      "Sentiment shift (positive coverage ratio delta)",
      "Share of voice vs competitors (movement)",
      "Source pickup analysis (which outlets covered the campaign)",
      "Source authority weighting (not all outlets are equal)",
      "Narrative resonance (did your message land?)",
      "AI engine pickup (did ChatGPT/Perplexity/Gemini/Claude cite the campaign?)",
      "Executive share of voice (CEO/CFO/CMO mentions delta)",
      "Topic penetration (which of your topics gained traction?)",
      "Geographic reach (Morocco vs Africa vs international)",
      "ROI calculation (vs. campaign cost)",
    ],
    whatsInside: [
      { section: "Executive Summary", desc: "Campaign impact score (0-100), top 3 wins, top 3 missed opportunities." },
      { section: "Before/After Dashboard", desc: "Side-by-side comparison: volume, sentiment, share of voice, AI visibility." },
      { section: "Volume Analysis", desc: "Article count spike, peak day, sustained lift vs baseline. Source breakdown." },
      { section: "Sentiment Shift", desc: "Positive coverage ratio before vs after. Which topics drove sentiment change?" },
      { section: "Share of Voice", desc: "Your SOV vs competitors — did the campaign move your share?" },
      { section: "Source Pickup", desc: "Which outlets covered the campaign? Authority × reach × sentiment per source." },
      { section: "Narrative Resonance", desc: "Did your campaign message become a narrative? Strength tracking pre/post." },
      { section: "AI Engine Pickup", desc: "Did AI engines start citing you after the campaign? Per-engine analysis." },
      { section: "Executive Visibility", desc: "CEO/CFO/CMO share of voice delta. Did your spokespeople get quoted?" },
      { section: "ROI Calculation", desc: "Campaign cost vs. reputation impact. Estimated MAD value of coverage uplift." },
    ],
    sampleQuestions: [
      "Did our PR campaign actually move the needle on sentiment?",
      "Which outlets gave us the best coverage?",
      "Did our campaign message become a narrative?",
      "Did AI engines start citing us after the campaign?",
      "How did our share of voice change vs competitors?",
      "What was the ROI of our PR spend?",
      "Did our CEO get quoted more after the campaign?",
      "Which topics gained traction from the campaign?",
    ],
    pricing: [
      { tier: "Single campaign", price: "10,000 MAD", frequency: "one campaign", features: ["14-page PDF", "Before/after dashboard", "30-day access", "1-hour debrief"] },
      { tier: "4 campaigns/year", price: "7,500 MAD", frequency: "per campaign", features: ["4 reports per year", "Cumulative dashboard", "Campaign comparison", "Quarterly debrief"] },
      { tier: "Monthly (Agency)", price: "6,000 MAD", frequency: "per month", features: ["12 reports per year", "Multi-campaign tracking", "White-label option", "Dedicated analyst", "Client-ready export"] },
    ],
  },

  "deep-dive": {
    slug: "deep-dive",
    eyebrow: "Deep Dive Reports",
    title: "Bespoke research on any topic, competitor, or market.",
    tagline: "Have a strategic question that doesn't fit any template? We'll build a custom report.",
    intro: "Some questions don't fit a template. 'Should we acquire Company X?' 'How is the regulatory environment for fintech evolving in West Africa?' 'What's the perception gap between our brand and our parent company?' Our senior analysts build bespoke Deep Dive Reports — powered by HarchIQ data, augmented with human research.",
    color: "#8A5520",
    pages: 30,
    deliveryTime: "10 business days",
    format: "PDF + executive presentation + 2-hour workshop",
    stats: [
      { value: "30", label: "pages, bespoke" },
      { value: "10", label: "business days delivery" },
      { value: "2h", label: "analyst workshop included" },
      { value: "Custom", label: "research questions" },
    ],
    whatsIncluded: [
      "Custom research scope defined with you",
      "Bespoke data analysis (HarchIQ + manual research)",
      "30-page board-ready PDF",
      "Executive presentation deck (20 slides)",
      "2-hour analyst workshop (in-person at CFC or virtual)",
      "Follow-up Q&A document",
      "30-day access to supporting dashboard",
      "Raw data export (CSV/Excel)",
      "Methodology documentation",
      "Source citation list",
      "Confidentiality guaranteed (NDA available)",
      "Custom branding (your logo, colors)",
    ],
    whatsInside: [
      { section: "Custom Executive Summary", desc: "Tailored to your strategic question. 2 pages." },
      { section: "Research Question Deep Dive", desc: "Multi-angle analysis of your specific question, using all HarchIQ data + manual research." },
      { section: "Data Analysis", desc: "Custom charts, tables, visualizations built specifically for this report." },
      { section: "Stakeholder Perspectives", desc: "How different stakeholders (media, analysts, regulators, customers) view the question." },
      { section: "Scenario Analysis", desc: "Best case / base case / worst case scenarios for your strategic decision." },
      { section: "Recommendations", desc: "Clear, actionable recommendations tied to your strategic question." },
      { section: "Implementation Roadmap", desc: "How to act on the recommendations — timeline, owners, KPIs." },
      { section: "Appendix", desc: "Full data tables, source citations, methodology, glossary." },
    ],
    sampleQuestions: [
      "Should we acquire Company X? What's the reputation risk?",
      "How is the fintech regulatory environment evolving in West Africa?",
      "What's the perception gap between our brand and our parent company?",
      "Which African markets should we expand into based on reputation?",
      "How will the new ESG regulation affect our industry's perception?",
      "What's the reputation impact of our CEO's recent statements?",
      "How are NGOs viewing our supply chain practices?",
      "What narrative should we build for our 2027 strategic plan?",
    ],
    pricing: [
      { tier: "Standard", price: "45,000 MAD", frequency: "one report", features: ["30-page PDF", "20-slide deck", "2-hour workshop", "30-day dashboard", "Raw data export"] },
      { tier: "Strategic", price: "65,000 MAD", frequency: "one report", features: ["40-page PDF", "30-slide deck", "Half-day workshop", "90-day dashboard", "Follow-up Q&A", "Senior partner lead"] },
      { tier: "Multi-report", price: "35,000 MAD", frequency: "per report (3+)", features: ["3+ reports per year", "Cumulative dashboard", "Quarterly workshop", "Dedicated analyst", "Priority scheduling", "Cross-report synthesis"] },
    ],
  },
};
