// Expertise data — separated from the client component to avoid
// server/client serialization issues during prerendering.
import type { ExpertiseData } from "./ExpertisePageTemplate";

export const EXPERTISE_DATA: Record<string, ExpertiseData> = {
  "enterprise-risk": {
    slug: "enterprise-risk",
    eyebrow: "Enterprise Risk",
    title: "Identify risks before they materialize.",
    tagline: "32 risk categories. 6 industries. Real-time detection with Frequency × Impact × Velocity scoring.",
    intro: "Enterprise risk has never been more interconnected. A supply chain disruption in Asia can trigger a regulatory inquiry in Casablanca. A cyber attack on a vendor can become a front-page scandal. Harch AI scans 30+ media sources 24/7 to detect emerging risks before they hit your inbox — and tells you exactly what to do about them.",
    color: "#A0524B",
    stats: [
      { value: "32", label: "risk categories tracked" },
      { value: "6", label: "industries profiled" },
      { value: "24/7", label: "monitoring" },
      { value: "<5min", label: "alert latency" },
    ],
    pillars: [
      { title: "Predictive, not reactive", desc: "Unlike traditional risk assessments that look backward, HarchIQ identifies emerging threats as they develop across news, regulatory filings, and industry reports.", icon: "◆" },
      { title: "Industry-specific mapping", desc: "Banking has different risks than Mining. Our industry profiles apply weighting (Banking × 1.8 on fraud, Mining × 1.7 on accidents) for accurate scoring.", icon: "▲" },
      { title: "Real-time evolution", desc: "Risk landscapes shift daily. We track trajectory (rising/stable/declining) and momentum — not just snapshots.", icon: "◉" },
      { title: "Actionable mitigation", desc: "Every detected risk comes with a HarchIQ-generated mitigation plan: who to engage, what to prepare, when to act.", icon: "⚙" },
    ],
    useCases: [
      "Detect supply chain disruptions 72 hours before they impact operations",
      "Monitor regulatory changes across BAM, AMMC, ANRT, and customs authorities",
      "Track competitor cyber incidents and assess your own exposure",
      "Identify labor dispute signals before strikes are called",
      "Monitor geopolitical tensions affecting your African operations",
      "Get early warning of ESG controversies in your supply chain",
      "Track negative sentiment clusters forming on social media",
      "Benchmark your risk profile against industry peers",
    ],
    features: [
      "32 risk event categories (geopolitical, operational, financial, environmental, legal, consumer, technology, governance)",
      "Risk scoring: Frequency × Impact Severity × Velocity (0-100 composite)",
      "Industry-specific weighting (Banking, Telco, Mining, Retail, Aviation, Energy, Agro-industry, Cement)",
      "Risk trajectory tracking: rising · stable · declining",
      "Real-time WhatsApp alerts when risk velocity > 50% in 24h",
      "AI-generated mitigation recommendations per risk",
      "Emerging risk detection — catch risks before mainstream media",
      "Industry Risk Dashboard with category breakdown",
      "Quarterly risk review with senior analyst",
      "Crisis playbook templates for top 10 risks",
      "Custom risk taxonomy (define your own categories)",
      "Sub-processor risk monitoring (4th-party visibility)",
    ],
    visualSections: [
      {
        title: "Risk heatmap by industry × category",
        description: "Risk scores (0–100) across 6 industries and 7 risk categories. Darker cells flag elevated exposure requiring active mitigation.",
        type: "heatmap",
        fullWidth: true,
        data: {
          rows: ["Banking", "Telecom", "Mining", "Aviation", "Retail", "Energy"],
          cols: ["Cyber", "Fraud", "Regulatory", "Operational", "Labor", "ESG", "Geopolitical"],
          colorScale: ["#F5F0EF", "#E8C9C5", "#D49A93", "#A0524B", "#7A3A33"],
          cells: [
            { row: "Banking", col: "Cyber", value: 82 }, { row: "Banking", col: "Fraud", value: 81 }, { row: "Banking", col: "Regulatory", value: 75 }, { row: "Banking", col: "Operational", value: 58 }, { row: "Banking", col: "Labor", value: 42 }, { row: "Banking", col: "ESG", value: 38 }, { row: "Banking", col: "Geopolitical", value: 35 },
            { row: "Telecom", col: "Cyber", value: 78 }, { row: "Telecom", col: "Fraud", value: 55 }, { row: "Telecom", col: "Regulatory", value: 65 }, { row: "Telecom", col: "Operational", value: 62 }, { row: "Telecom", col: "Labor", value: 60 }, { row: "Telecom", col: "ESG", value: 45 }, { row: "Telecom", col: "Geopolitical", value: 48 },
            { row: "Mining", col: "Cyber", value: 48 }, { row: "Mining", col: "Fraud", value: 52 }, { row: "Mining", col: "Regulatory", value: 60 }, { row: "Mining", col: "Operational", value: 75 }, { row: "Mining", col: "Labor", value: 68 }, { row: "Mining", col: "ESG", value: 80 }, { row: "Mining", col: "Geopolitical", value: 58 },
            { row: "Aviation", col: "Cyber", value: 65 }, { row: "Aviation", col: "Fraud", value: 40 }, { row: "Aviation", col: "Regulatory", value: 55 }, { row: "Aviation", col: "Operational", value: 78 }, { row: "Aviation", col: "Labor", value: 50 }, { row: "Aviation", col: "ESG", value: 62 }, { row: "Aviation", col: "Geopolitical", value: 65 },
            { row: "Retail", col: "Cyber", value: 70 }, { row: "Retail", col: "Fraud", value: 58 }, { row: "Retail", col: "Regulatory", value: 45 }, { row: "Retail", col: "Operational", value: 50 }, { row: "Retail", col: "Labor", value: 55 }, { row: "Retail", col: "ESG", value: 48 }, { row: "Retail", col: "Geopolitical", value: 30 },
            { row: "Energy", col: "Cyber", value: 60 }, { row: "Energy", col: "Fraud", value: 45 }, { row: "Energy", col: "Regulatory", value: 52 }, { row: "Energy", col: "Operational", value: 72 }, { row: "Energy", col: "Labor", value: 58 }, { row: "Energy", col: "ESG", value: 78 }, { row: "Energy", col: "Geopolitical", value: 70 },
          ],
        },
      },
      {
        title: "Risk distribution across 32 categories",
        description: "Share of monitored risk events by category over the last 90 days. Operational and Financial risks dominate the Moroccan corporate landscape.",
        type: "donut",
        fullWidth: false,
        data: {
          centerValue: "32",
          centerLabel: "Categories",
          segments: [
            { label: "Operational", value: 28, color: "#A0524B" },
            { label: "Financial", value: 22, color: "#7A3A33" },
            { label: "Legal", value: 14, color: "#B87333" },
            { label: "Geopolitical", value: 12, color: "#4A5D6E" },
            { label: "Consumer", value: 10, color: "#8B9DAF" },
            { label: "Environmental", value: 8, color: "#6FA386" },
            { label: "Technology", value: 6, color: "#A8C9B5" },
          ],
        },
      },
      {
        title: "Top 10 emerging risks — Harch 100 composite",
        description: "Ranked by Frequency × Impact × Velocity (0–100). These ten risks are currently driving the highest exposure across our monitored universe.",
        type: "hbar",
        fullWidth: true,
        data: {
          items: [
            { label: "Financial Fraud", value: 81, color: "#7A3A33" },
            { label: "Cyber Attack", value: 78, color: "#A0524B" },
            { label: "Operational Accident", value: 75, color: "#B87333" },
            { label: "Data Breach", value: 70, color: "#A0524B" },
            { label: "Labor Dispute", value: 60, color: "#B87333" },
            { label: "Regulatory Violation", value: 55, color: "#4A5D6E" },
            { label: "Brand Reputation", value: 50, color: "#8B9DAF" },
            { label: "Supply Chain", value: 48, color: "#8B9DAF" },
            { label: "Climate Event", value: 45, color: "#6FA386" },
            { label: "Geopolitical Tension", value: 42, color: "#4A5D6E" },
          ],
        },
      },
      {
        title: "Industry risk profile — Banking vs Telecom vs Mining",
        description: "Multi-axis comparison (0–100) across 7 risk dimensions. Each industry carries a distinct risk signature requiring tailored mitigation playbooks.",
        type: "radar",
        fullWidth: false,
        data: {
          axes: ["Geopolitical", "Operational", "Financial", "Environmental", "Legal", "Consumer", "Technology"],
          series: [
            { name: "Banking", color: "#4A5D6E", values: [35, 58, 81, 38, 75, 55, 82] },
            { name: "Telecom", color: "#A0524B", values: [48, 62, 55, 45, 65, 60, 78] },
            { name: "Mining", color: "#B87333", values: [58, 75, 52, 80, 60, 50, 48] },
          ],
        },
      },
    ],
    quote: {
      text: "Harch AI allows us to give clients early warning of threats to their reputation. We help them plan an efficient response, and in that way provide them with a unique, impactful service.",
      author: "PR Agency Director",
      role: "Senior Partner, Casablanca",
    },
    relatedReports: [
      { title: "Risk Reports", href: "/atelier/insight-reports/risk" },
      { title: "Risk Tracker", href: "/atelier/risk-tracker" },
      { title: "Reputation Risk Reports", href: "/atelier/insight-reports/reputation-risk" },
    ],
  },

  "reputation-risk": {
    slug: "reputation-risk",
    eyebrow: "Reputation Risk",
    title: "Perception shifts can damage brand value overnight.",
    tagline: "Monitor narrative drift, sentiment swings, and emerging threats to your reputation — in real time.",
    intro: "Reputation is the most valuable intangible asset on your balance sheet — and the most fragile. A single viral tweet, a misleading article, or a competitor's narrative can erase years of brand building. Harch AI detects reputation risks as they form, before they become crises, so you can respond with precision rather than panic.",
    color: "#A02828",
    stats: [
      { value: "5", label: "narratives tracked per company" },
      { value: "10", label: "topic clusters monitored" },
      { value: "108+", label: "sentiment lexicon words (FR/AR/EN)" },
      { value: "Real-time", label: "sentiment shift alerts" },
    ],
    pillars: [
      { title: "Narrative detection", desc: "We identify the 5 dominant narratives forming around your brand — with strength, sentiment, and trajectory. Spot the story before it becomes the story.", icon: "◆" },
      { title: "Entity-level sentiment", desc: "Not just keyword mentions. We track sentiment at the entity level — your company, your CEO, your products, your competitors — in every article.", icon: "▲" },
      { title: "Trilingual precision", desc: "French, Arabic, and English handled natively. Darija and code-switching detected and flagged for human review. 108+ word sentiment lexicon per language.", icon: "◉" },
      { title: "Crisis early warning", desc: "WhatsApp alerts when negative sentiment velocity exceeds threshold. Get notified within 5 minutes of a shift — not the next morning.", icon: "⚠" },
    ],
    useCases: [
      "Detect negative narrative formation 24-48 hours before mainstream coverage",
      "Monitor sentiment by source — know which outlets matter most",
      "Track reputation impact of executive statements and interviews",
      "Benchmark reputation score against top 5 competitors weekly",
      "Get alerted when negative sentiment velocity spikes",
      "Measure reputation recovery after a crisis",
      "Identify which products/segments are dragging down brand sentiment",
      "Track CEO and C-suite personal reputation separately from corporate",
    ],
    features: [
      "5 dominant narratives with strength scoring (0-100) and trajectory (emerging/growing/peak/declining)",
      "10 topic clusters (financial results, leadership, products, ESG, M&A, digital, crisis, expansion, partnerships, regulation)",
      "Entity-level sentiment (company, CEO, products, competitors in same article)",
      "Trilingual sentiment analysis (FR · AR · EN) with 108+ word lexicon per language",
      "Sentiment shift alerts (>10% change in 24h triggers WhatsApp)",
      "Reputation score (0-100) with 4 components: sentiment × AI visibility × volume × authority",
      "Reputation pillars: Innovation / Performance / Purpose (Signal AI 500 style)",
      "9 key themes: Collaborations, Products, Technology, Governance, Growth, Operations, CSR, Culture, Sustainability",
      "Quarterly trend tracking (4Q historical)",
      "Crisis playbook templates",
      "Source authority scoring",
      "Harch 100 ranking position",
    ],
    visualSections: [
      {
        title: "Narrative strength over time",
        description: "Trajectory of the 5 dominant narratives around a flagship Moroccan company across Q1–Q4 2026. Strength scored 0–100; rising curves indicate growing narrative dominance.",
        type: "line",
        fullWidth: true,
        data: {
          xLabels: ["Q1", "Q2", "Q3", "Q4"],
          yMax: 100,
          series: [
            { name: "Pan-African expansion", color: "#A02828", points: [58, 72, 80, 86] },
            { name: "Digital transformation", color: "#4A5D6E", points: [45, 55, 68, 78] },
            { name: "ESG leadership", color: "#6FA386", points: [38, 48, 60, 72] },
            { name: "Q2 results", color: "#B87333", points: [12, 30, 56, 56] },
            { name: "Labor tensions", color: "#8B9DAF", points: [28, 35, 40, 42] },
          ],
        },
      },
      {
        title: "Sentiment by language",
        description: "Distribution of monitored coverage across the three primary media languages in Morocco. French remains dominant but Arabic is growing fastest.",
        type: "donut",
        fullWidth: false,
        data: {
          centerValue: "3",
          centerLabel: "Languages",
          segments: [
            { label: "French (FR)", value: 68, color: "#A02828" },
            { label: "Arabic (AR)", value: 22, color: "#B87333" },
            { label: "English (EN)", value: 10, color: "#4A5D6E" },
          ],
        },
      },
      {
        title: "Top 5 narratives — strength & sentiment",
        description: "Each narrative is coloured by its prevailing sentiment. Negative-sentiment narratives demand immediate comms intervention.",
        type: "hbar",
        fullWidth: true,
        data: {
          items: [
            { label: "Pan-African expansion", value: 86, color: "#6FA386", sublabel: "Positive" },
            { label: "Digital transformation", value: 78, color: "#6FA386", sublabel: "Positive" },
            { label: "ESG leadership", value: 72, color: "#A8C9B5", sublabel: "Mostly positive" },
            { label: "Q2 results", value: 56, color: "#B87333", sublabel: "Mixed" },
            { label: "Labor tensions", value: 42, color: "#A02828", sublabel: "Negative" },
          ],
        },
      },
      {
        title: "Narrative × topic cluster — article volume",
        description: "Volume of articles tagged across 5 narratives and 10 topic clusters over the last 90 days. Hotspots indicate where narrative attention is concentrating.",
        type: "heatmap",
        fullWidth: true,
        data: {
          rows: ["Pan-African expansion", "Digital transformation", "ESG leadership", "Q2 results", "Labor tensions"],
          cols: ["Financial", "Leadership", "Products", "ESG", "M&A", "Digital", "Crisis", "Expansion", "Partnerships", "Regulation"],
          colorScale: ["#F4F4F5", "#E8D5D2", "#D49A93", "#A02828", "#7A1E1E"],
          cells: [
            { row: "Pan-African expansion", col: "Financial", value: 8 }, { row: "Pan-African expansion", col: "Leadership", value: 6 }, { row: "Pan-African expansion", col: "Products", value: 4 }, { row: "Pan-African expansion", col: "ESG", value: 3 }, { row: "Pan-African expansion", col: "M&A", value: 12 }, { row: "Pan-African expansion", col: "Digital", value: 5 }, { row: "Pan-African expansion", col: "Crisis", value: 2 }, { row: "Pan-African expansion", col: "Expansion", value: 18 }, { row: "Pan-African expansion", col: "Partnerships", value: 14 }, { row: "Pan-African expansion", col: "Regulation", value: 5 },
            { row: "Digital transformation", col: "Financial", value: 7 }, { row: "Digital transformation", col: "Leadership", value: 8 }, { row: "Digital transformation", col: "Products", value: 12 }, { row: "Digital transformation", col: "ESG", value: 4 }, { row: "Digital transformation", col: "M&A", value: 3 }, { row: "Digital transformation", col: "Digital", value: 20 }, { row: "Digital transformation", col: "Crisis", value: 2 }, { row: "Digital transformation", col: "Expansion", value: 6 }, { row: "Digital transformation", col: "Partnerships", value: 7 }, { row: "Digital transformation", col: "Regulation", value: 6 },
            { row: "ESG leadership", col: "Financial", value: 5 }, { row: "ESG leadership", col: "Leadership", value: 6 }, { row: "ESG leadership", col: "Products", value: 3 }, { row: "ESG leadership", col: "ESG", value: 22 }, { row: "ESG leadership", col: "M&A", value: 2 }, { row: "ESG leadership", col: "Digital", value: 4 }, { row: "ESG leadership", col: "Crisis", value: 3 }, { row: "ESG leadership", col: "Expansion", value: 5 }, { row: "ESG leadership", col: "Partnerships", value: 6 }, { row: "ESG leadership", col: "Regulation", value: 8 },
            { row: "Q2 results", col: "Financial", value: 24 }, { row: "Q2 results", col: "Leadership", value: 14 }, { row: "Q2 results", col: "Products", value: 6 }, { row: "Q2 results", col: "ESG", value: 5 }, { row: "Q2 results", col: "M&A", value: 3 }, { row: "Q2 results", col: "Digital", value: 4 }, { row: "Q2 results", col: "Crisis", value: 2 }, { row: "Q2 results", col: "Expansion", value: 4 }, { row: "Q2 results", col: "Partnerships", value: 3 }, { row: "Q2 results", col: "Regulation", value: 5 },
            { row: "Labor tensions", col: "Financial", value: 4 }, { row: "Labor tensions", col: "Leadership", value: 10 }, { row: "Labor tensions", col: "Products", value: 2 }, { row: "Labor tensions", col: "ESG", value: 3 }, { row: "Labor tensions", col: "M&A", value: 1 }, { row: "Labor tensions", col: "Digital", value: 2 }, { row: "Labor tensions", col: "Crisis", value: 18 }, { row: "Labor tensions", col: "Expansion", value: 2 }, { row: "Labor tensions", col: "Partnerships", value: 1 }, { row: "Labor tensions", col: "Regulation", value: 8 },
          ],
        },
      },
    ],
    quote: {
      text: "Harch AI's reporting doesn't just help us understand current conditions — it illuminates our path forward. Their insights have directly influenced the direction of our communications strategy.",
      author: "Director of Communications",
      role: "Moroccan Financial Institution",
    },
    relatedReports: [
      { title: "Reputation Risk Reports", href: "/atelier/insight-reports/reputation-risk" },
      { title: "Reputation Reports", href: "/atelier/insight-reports/reputation" },
      { title: "Harch 100 Ranking", href: "/atelier/harch-100" },
    ],
  },

  "pr-comms": {
    slug: "pr-comms",
    eyebrow: "PR & Comms",
    title: "Augment your Comms team with real-time intelligence.",
    tagline: "From tactical delivery to strategic influence — the shift every Comms leader needs to make.",
    intro: "Comms leaders are under pressure to take on a more strategic role. 85% of C-suite leaders prioritize reputation over profit margin when making decisions — and they're looking to Comms for guidance. But the overwhelming volume of data is the #1 blocker. Harch AI eliminates that blocker, freeing Comms teams to focus on strategy, not spreadsheet maintenance.",
    color: "#4A7B5F",
    stats: [
      { value: "40h", label: "saved per week (avg)" },
      { value: "85%", label: "C-suite prioritize reputation" },
      { value: "30+", label: "media sources automated" },
      { value: "Daily", label: "WhatsApp digest at 7am" },
    ],
    pillars: [
      { title: "Strategic, not tactical", desc: "Stop spending 40 hours/week on coverage reports. Harch AI automates monitoring so your team can focus on advising the C-suite.", icon: "◆" },
      { title: "Measurement that matters", desc: "Move beyond AVE (ad value equivalence). Track share of voice, sentiment, AI visibility, narrative strength — the metrics executives care about.", icon: "▲" },
      { title: "Real-time intelligence", desc: "Daily WhatsApp digest at 7am Casa time. Real-time crisis alerts. Weekly exec briefing. Monthly board-ready PDF. Your cadence, our pipeline.", icon: "◉" },
      { title: "Board-ready output", desc: "Every report is designed for the boardroom. Clean PDFs, executive summaries, action plans. No more apologies for ugly PR reports.", icon: "✦" },
    ],
    useCases: [
      "Automate daily media monitoring — save 40 hours/week",
      "Generate board-ready PDF reports in 1 click",
      "Track PR campaign impact with quantifiable metrics",
      "Benchmark share of voice vs competitors weekly",
      "Get crisis alerts within 5 minutes of negative sentiment spike",
      "Measure executive share of voice and media training ROI",
      "Track narrative resonance across earned media",
      "Justify PR budget with data-driven impact reports",
    ],
    features: [
      "Daily WhatsApp digest (7am Casa time, 30-second read)",
      "Weekly executive briefing (Monday 8am, 5-minute read)",
      "Monthly board-ready PDF (20 pages, delivered 1st of month)",
      "Real-time crisis alerts (negative sentiment velocity > 50%)",
      "Share of voice tracking vs up to 10 competitors",
      "PR campaign measurement (before/during/after)",
      "Executive share of voice (CEO, CFO, CTO tracked separately)",
      "Media training ROI measurement",
      "Source authority scoring — know which outlets matter",
      "Coverage reports in 1 click (custom date ranges)",
      "Slack + Microsoft Teams integration",
      "Multi-language delivery (FR, AR, EN)",
    ],
    visualSections: [
      {
        title: "Hours saved per week, by task",
        description: "Automation impact across five core Comms workflows. Total time freed: 40 hours/week — equivalent to one full-time analyst.",
        type: "bars",
        fullWidth: false,
        data: {
          height: 240,
          format: "hours",
          items: [
            { label: "Coverage reporting", value: 16, color: "#4A7B5F" },
            { label: "Sentiment analysis", value: 8, color: "#6FA386" },
            { label: "Crisis monitoring", value: 6, color: "#8B9DAF" },
            { label: "Competitor tracking", value: 5, color: "#4A5D6E" },
            { label: "Exec briefing prep", value: 5, color: "#A8C9B5" },
          ],
        },
      },
      {
        title: "Before vs After Harch AI",
        description: "Same team, same mandate, dramatically different output. The shift from manual to AI-augmented transforms Comms from cost centre to strategic advisor.",
        type: "statcards",
        fullWidth: true,
        data: {
          cards: [
            { value: "40h", label: "Weekly manual effort", sublabel: "Before — 8 sources monitored, monthly reports, 24h alert latency", color: "#B87333" },
            { value: "5h", label: "Weekly oversight effort", sublabel: "After — 30+ sources automated, daily reports, 5min alert latency", color: "#4A7B5F" },
          ],
        },
      },
      {
        title: "Comms maturity score",
        description: "Industry benchmark: most Moroccan Comms teams sit between 40–55 (Tactical). Teams using Harch AI reach 75+ (Strategic) within 90 days.",
        type: "gauge",
        fullWidth: false,
        data: {
          score: 75,
          label: "Strategic",
          color: "#4A7B5F",
        },
      },
      {
        title: "Share of voice — 3 competitors over 2026",
        description: "Weekly share of earned-media voice across Q1–Q4 2026. After adopting Harch AI in Q2, the monitored company overtook both peers by Q4.",
        type: "line",
        fullWidth: true,
        data: {
          xLabels: ["Q1", "Q2", "Q3", "Q4"],
          yMax: 60,
          series: [
            { name: "Your company", color: "#4A7B5F", points: [22, 28, 38, 48] },
            { name: "Competitor A", color: "#A0524B", points: [35, 33, 30, 28] },
            { name: "Competitor B", color: "#8B9DAF", points: [28, 27, 24, 22] },
          ],
        },
      },
    ],
    quote: {
      text: "After 20+ years of ill-thought-through PR reports put in front of executives, we finally have a reporting mechanism with Harch AI that's seen as truly strategic across the business.",
      author: "Global Head of External Communications",
      role: "African Holdings Group",
    },
    relatedReports: [
      { title: "Media Impact Reports", href: "/atelier/insight-reports/media-impact" },
      { title: "Reputation Reports", href: "/atelier/insight-reports/reputation" },
      { title: "Deep Dive Reports", href: "/atelier/insight-reports/deep-dive" },
    ],
  },

  "esg": {
    slug: "esg",
    eyebrow: "ESG",
    title: "Track sustainability narratives and greenwashing risks.",
    tagline: "Investors care. Regulators care. Media cares. Harch AI makes sure your ESG story lands.",
    intro: "ESG is no longer a compliance exercise — it's a reputation imperative. Investors use ESG ratings to allocate capital. Regulators are tightening disclosure requirements. Media scrutinize every sustainability claim for greenwashing. Harch AI tracks your ESG narrative across all these audiences, identifies greenwashing risks before they erupt, and measures the actual media impact of your sustainability initiatives.",
    color: "#4A7B5F",
    stats: [
      { value: "3", label: "ESG pillars tracked (E/S/G)" },
      { value: "9", label: "ESG themes monitored" },
      { value: "Real-time", label: "greenwashing risk alerts" },
      { value: "Quarterly", label: "ESG perception reports" },
    ],
    pillars: [
      { title: "Sustainability narrative tracking", desc: "Track how your ESG initiatives are received in media. Are you seen as a leader, a laggard, or a greenwasher? We measure perception, not just volume.", icon: "◆" },
      { title: "Greenwashing risk detection", desc: "HarchIQ flags claims that could be challenged — vague language, unsupported statistics, inconsistent messaging across channels. Catch risks before NGOs and journalists do.", icon: "▲" },
      { title: "Investor sentiment monitoring", desc: "Track how ESG analysts, rating agencies, and institutional investors are talking about your ESG performance. Anticipate ratings changes.", icon: "◉" },
      { title: "Regulatory horizon scanning", desc: "Stay ahead of ESG disclosure requirements: CSRD, SFDR, Moroccan Loi 30-21 on sustainable development, and African regional frameworks.", icon: "⚙" },
    ],
    useCases: [
      "Track sentiment of ESG coverage (positive vs negative perception)",
      "Detect greenwashing accusations before they go viral",
      "Measure media impact of your sustainability report launch",
      "Benchmark ESG narrative vs industry peers",
      "Monitor investor sentiment around ESG ratings",
      "Track regulatory changes affecting ESG disclosure",
      "Identify which ESG topics resonate most with media",
      "Prepare for AGM with sentiment analysis of shareholder concerns",
    ],
    features: [
      "3 ESG pillars: Environmental, Social, Governance",
      "9 ESG themes: Climate, Biodiversity, Water, Circularity, DEI, Human Rights, Labor, Board, Ethics",
      "Greenwashing risk scoring per claim (0-100)",
      "ESG sentiment tracking (positive/neutral/negative per pillar)",
      "Investor sentiment analysis (analyst reports, ratings agencies)",
      "ESG regulatory horizon scanning (EU CSRD, SFDR, MA Loi 30-21)",
      "Sustainability report launch impact measurement",
      "ESG benchmark vs industry peers",
      "Quarterly ESG perception report (PDF, 15 pages)",
      "AGM sentiment preparation pack",
      "NGO and activist monitoring",
      "CDP and TCFD alignment tracking",
    ],
    visualSections: [
      {
        title: "ESG profile — 5 Moroccan leaders across 6 themes",
        description: "Perception scores (0–100) across six ESG themes derived from media coverage, analyst commentary, and NGO reporting. Higher is stronger perceived performance.",
        type: "radar",
        fullWidth: true,
        data: {
          axes: ["Climate", "Biodiversity", "DEI", "Human Rights", "Labor", "Ethics"],
          series: [
            { name: "OCP Group", color: "#6FA386", values: [82, 75, 68, 72, 70, 78] },
            { name: "Attijariwafa Bank", color: "#4A5D6E", values: [70, 55, 78, 75, 72, 80] },
            { name: "Bank of Africa", color: "#B87333", values: [68, 52, 80, 76, 74, 76] },
            { name: "Maroc Telecom", color: "#A0524B", values: [65, 58, 72, 68, 70, 72] },
            { name: "Managem", color: "#8B9DAF", values: [58, 62, 60, 65, 62, 66] },
          ],
        },
      },
      {
        title: "Greenwashing risk — Moroccan corporate average",
        description: "Composite score (0–100) across claim specificity, evidence backing, and channel consistency. Lower is safer; below 40 is considered Low risk.",
        type: "gauge",
        fullWidth: false,
        data: {
          score: 35,
          label: "Low risk",
          color: "#6FA386",
        },
      },
      {
        title: "ESG sentiment by pillar",
        description: "Share of positive sentiment in ESG-tagged coverage, split by pillar. Environmental leads thanks to climate disclosure momentum; Governance lags on board-diversity scrutiny.",
        type: "hbar",
        fullWidth: false,
        data: {
          format: "percent",
          items: [
            { label: "Environmental", value: 78, color: "#6FA386" },
            { label: "Social", value: 72, color: "#4A7B5F" },
            { label: "Governance", value: 68, color: "#4A5D6E" },
          ],
        },
      },
      {
        title: "ESG coverage volume — 2026 trend",
        description: "Total ESG-tagged articles per quarter across the 30+ monitored sources. Coverage has nearly doubled year-on-year, reflecting rising investor and regulator scrutiny.",
        type: "line",
        fullWidth: true,
        data: {
          xLabels: ["Q1", "Q2", "Q3", "Q4"],
          series: [
            { name: "ESG articles", color: "#6FA386", points: [340, 420, 510, 640] },
          ],
        },
      },
    ],
    quote: {
      text: "Harch AI helped us catch a greenwashing accusation 48 hours before it went public. We were able to prepare our response and the story never gained traction.",
      author: "Sustainability Director",
      role: "Moroccan Industrial Group",
    },
    relatedReports: [
      { title: "Deep Dive Reports", href: "/atelier/insight-reports/deep-dive" },
      { title: "Reputation Reports", href: "/atelier/insight-reports/reputation" },
      { title: "Media Impact Reports", href: "/atelier/insight-reports/media-impact" },
    ],
  },

  "regulation": {
    slug: "regulation",
    eyebrow: "Regulation",
    title: "Stay ahead of regulatory changes across Morocco & Africa.",
    tagline: "BAM, AMMC, ANRT, customs, ONSSA — every regulator that touches your business, monitored 24/7.",
    intro: "Regulatory risk has exploded. New laws on data protection (Loi 09-08), financial compliance (BAM circulars), telecom regulation (ANRT), food safety (ONSSA), and ESG disclosure (Loi 30-21) create a constant stream of obligations. Missing one isn't an option. Harch AI monitors every Moroccan and African regulator, tracks proposed changes before they become law, and tells you exactly what each change means for your business.",
    color: "#8A5520",
    stats: [
      { value: "12+", label: "Moroccan regulators tracked" },
      { value: "8", label: "African jurisdictions covered" },
      { value: "Real-time", label: "regulatory change alerts" },
      { value: "Quarterly", label: "compliance impact reports" },
    ],
    pillars: [
      { title: "Regulatory monitoring", desc: "We track every Moroccan regulator (BAM, AMMC, ANRT, ONSSA, ANAC, CNDP, ANCFCC, ONEE, AMMR) plus key African jurisdictions (UEMOA, CEMAC, AfCFTA).", icon: "◆" },
      { title: "Change impact analysis", desc: "When a new regulation drops, HarchIQ analyzes which of your business units, products, and processes are affected — and what you need to do.", icon: "▲" },
      { title: "Compliance narrative tracking", desc: "Monitor how media covers regulatory violations, fines, and enforcement actions in your industry. Spot patterns before they reach you.", icon: "◉" },
      { title: "Stakeholder mapping", desc: "Know who's who at each regulator. Track appointments, speeches, interviews, and public positions. Anticipate enforcement priorities.", icon: "⚙" },
    ],
    useCases: [
      "Get alerted within 1 hour of any new BAM or AMMC circular",
      "Track enforcement actions against competitors in your industry",
      "Monitor regulatory commentary in media (analyst opinions, expert quotes)",
      "Anticipate regulatory changes by tracking consultation documents",
      "Map stakeholder relationships at key regulators",
      "Benchmark your compliance narrative vs industry peers",
      "Prepare for regulatory inquiries with sentiment analysis",
      "Track Loi 09-08 (data protection) enforcement trends",
    ],
    features: [
      "12+ Moroccan regulators tracked (BAM, AMMC, ANRT, ONSSA, ANAC, CNDP, ANCFCC, ONEE, AMMR, CNDP, ANRT, Ministry of Economy)",
      "8 African jurisdictions (Morocco, Tunisia, Senegal, Côte d'Ivoire, Egypt, South Africa, Nigeria, Kenya)",
      "Real-time regulatory change alerts (WhatsApp + email within 1 hour)",
      "Change impact analysis (which business units/products affected)",
      "Enforcement action tracking (fines, sanctions, license revocations)",
      "Regulatory commentary monitoring (analyst opinions, expert quotes)",
      "Stakeholder mapping (regulator leadership, key advisors)",
      "Consultation document tracking (proposed laws before they pass)",
      "Compliance narrative benchmarking vs peers",
      "Quarterly compliance impact report (PDF, 20 pages)",
      "Crisis playbook for regulatory inquiries",
      "Custom regulatory taxonomy (define your own tracked bodies)",
    ],
    visualSections: [
      {
        title: "Regulator activity heatmap — 2026 circulars & decisions",
        description: "Volume of binding instruments (circulars, decisions, arrêtés) published per quarter by 12 Moroccan supervisors. Darker cells indicate heavier regulatory output.",
        type: "heatmap",
        fullWidth: true,
        data: {
          rows: ["BAM", "AMMC", "ANRT", "ONSSA", "ANAC", "CNDP", "ANCFCC", "ONEE", "AMMR", "Ministry of Economy", "CDVM", "DGII"],
          cols: ["Q1", "Q2", "Q3", "Q4"],
          colorScale: ["#F7F1EA", "#EAD3B8", "#D4A574", "#B87333", "#8A5520"],
          cells: [
            { row: "BAM", col: "Q1", value: 8 }, { row: "BAM", col: "Q2", value: 6 }, { row: "BAM", col: "Q3", value: 10 }, { row: "BAM", col: "Q4", value: 7 },
            { row: "AMMC", col: "Q1", value: 5 }, { row: "AMMC", col: "Q2", value: 7 }, { row: "AMMC", col: "Q3", value: 6 }, { row: "AMMC", col: "Q4", value: 9 },
            { row: "ANRT", col: "Q1", value: 4 }, { row: "ANRT", col: "Q2", value: 6 }, { row: "ANRT", col: "Q3", value: 8 }, { row: "ANRT", col: "Q4", value: 5 },
            { row: "ONSSA", col: "Q1", value: 6 }, { row: "ONSSA", col: "Q2", value: 5 }, { row: "ONSSA", col: "Q3", value: 7 }, { row: "ONSSA", col: "Q4", value: 8 },
            { row: "ANAC", col: "Q1", value: 2 }, { row: "ANAC", col: "Q2", value: 3 }, { row: "ANAC", col: "Q3", value: 4 }, { row: "ANAC", col: "Q4", value: 3 },
            { row: "CNDP", col: "Q1", value: 5 }, { row: "CNDP", col: "Q2", value: 8 }, { row: "CNDP", col: "Q3", value: 6 }, { row: "CNDP", col: "Q4", value: 10 },
            { row: "ANCFCC", col: "Q1", value: 3 }, { row: "ANCFCC", col: "Q2", value: 2 }, { row: "ANCFCC", col: "Q3", value: 4 }, { row: "ANCFCC", col: "Q4", value: 3 },
            { row: "ONEE", col: "Q1", value: 4 }, { row: "ONEE", col: "Q2", value: 5 }, { row: "ONEE", col: "Q3", value: 3 }, { row: "ONEE", col: "Q4", value: 6 },
            { row: "AMMR", col: "Q1", value: 2 }, { row: "AMMR", col: "Q2", value: 3 }, { row: "AMMR", col: "Q3", value: 2 }, { row: "AMMR", col: "Q4", value: 4 },
            { row: "Ministry of Economy", col: "Q1", value: 7 }, { row: "Ministry of Economy", col: "Q2", value: 9 }, { row: "Ministry of Economy", col: "Q3", value: 8 }, { row: "Ministry of Economy", col: "Q4", value: 11 },
            { row: "CDVM", col: "Q1", value: 4 }, { row: "CDVM", col: "Q2", value: 6 }, { row: "CDVM", col: "Q3", value: 5 }, { row: "CDVM", col: "Q4", value: 7 },
            { row: "DGII", col: "Q1", value: 6 }, { row: "DGII", col: "Q2", value: 5 }, { row: "DGII", col: "Q3", value: 7 }, { row: "DGII", col: "Q4", value: 8 },
          ],
        },
      },
      {
        title: "Regulatory risk by sector",
        description: "Composite regulatory exposure score (0–100) per sector, weighted by enforcement frequency, consultation volume, and media scrutiny intensity.",
        type: "hbar",
        fullWidth: false,
        data: {
          items: [
            { label: "Banking", value: 78, color: "#B87333" },
            { label: "Telecom", value: 65, color: "#8A5520" },
            { label: "Mining", value: 60, color: "#B87333" },
            { label: "Aviation", value: 55, color: "#D4A574" },
            { label: "Energy", value: 52, color: "#D4A574" },
            { label: "Agro-industry", value: 48, color: "#D4A574" },
            { label: "Retail", value: 45, color: "#EAD3B8" },
          ],
        },
      },
      {
        title: "Regulatory timeline — 8 key events shaping 2026",
        description: "Major regulatory developments tracked by Harch AI across Moroccan supervisors and ministries. Impact level reflects the breadth of affected businesses.",
        type: "timeline",
        fullWidth: true,
        data: {
          events: [
            { date: "15 Jan 2026", title: "BAM circular on climate-related financial risk disclosure", description: "New prudential expectations for banks on physical and transition risk modelling.", impact: "high" },
            { date: "28 Feb 2026", title: "AMMC updates insider-list enforcement guidelines", description: "Tighter reporting windows and an expanded definition of inside information.", impact: "medium" },
            { date: "10 Mar 2026", title: "CNDP framework on cross-border data transfers", description: "New adequacy-assessment requirements for EU-bound personal data flows.", impact: "high" },
            { date: "22 Apr 2026", title: "ANRT publishes 5G spectrum auction rules", description: "Coverage obligations and wholesale-access conditions finalised for operators.", impact: "high" },
            { date: "05 Jun 2026", title: "ONSSA food-labelling compliance deadline", description: "Mandatory front-of-pack nutritional scoring for packaged goods.", impact: "medium" },
            { date: "18 Jul 2026", title: "CDVM ESG disclosure requirements for listed companies", description: "Comply-or-explain regime across 9 ESG themes, phased over 2 years.", impact: "high" },
            { date: "30 Sep 2026", title: "Loi 30-21 implementing decree on sustainability reporting", description: "First mandatory sustainability report due for FY2026 large emitters.", impact: "high" },
            { date: "12 Nov 2026", title: "BAM finalises open-banking API framework", description: "Standardised APIs and consent flows for third-party payment initiators.", impact: "medium" },
          ],
        },
      },
      {
        title: "Compliance burden — Moroccan corporate average",
        description: "Composite index (0–100) blending regulatory change velocity, compliance spend, and enforcement intensity. Above 60 is considered Elevated.",
        type: "gauge",
        fullWidth: false,
        data: {
          score: 68,
          label: "Elevated",
          color: "#B87333",
        },
      },
    ],
    quote: {
      text: "We were alerted to a BAM circular 4 hours after publication — and 3 days before our competitors noticed. That head start gave us time to prepare a compliant response.",
      author: "Chief Compliance Officer",
      role: "Moroccan Bank",
    },
    relatedReports: [
      { title: "Risk Reports", href: "/atelier/insight-reports/risk" },
      { title: "Deep Dive Reports", href: "/atelier/insight-reports/deep-dive" },
      { title: "Risk Tracker", href: "/atelier/risk-tracker" },
    ],
  },
};
